<?php

#################################################################################################### --- DESCRIPTION

/**
 * Produces a binary string representation of the specified file.
 * 
 * This function aims to provide some validation for files uploaded by users.
 * 
 * If the file identifies as an image file, we try to recreate it using the GD library.
 * If the file is not a valid image file, the recreation process will fail and FALSE will be returned.
 * A successfully recreated image will not have any EXIF metadata apart from what is generated by GD,
 * ie. the original file's EXIF metadata will have been stripped away.
 * The binary string will be produced from the recreated image.
 * 
 * For all other file types, the binary string is produced from the file's contents.
 * 
 * Independently of file type, the binary string is scanned for occurences
 * of potentially malicious strings or code injections.
 * 
 * ATTENTION: ALWAYS use this function to process files that are provided/uploaded by users.
 * 
 * ATTENTION: NEVER "include" files that are provided/uploaded by users.
 * 
 * @param   string        $filePath   The location (path) of the original file.
 * 
 * @return  string|false              Returns a binary string which represents the original file,
 *                                    or FALSE if checks and validations fail.
 */

#################################################################################################### --- FUNCTION DECLARATION

function getBinaryString ($filePath) {
  
  # Get the file's MIME type, ie. what the file is identifying as.
  
  $finfo = finfo_open();
  
  $mimeType = finfo_file ($finfo, $filePath, FILEINFO_MIME_TYPE);
  
  finfo_close ($finfo);
  
  // ----------
  
  # Check whether the file's MIME type is in our whitelist.
  
  if ( ! array_key_exists ($mimeType, MIME_TYPES)) {
    
    # This type of file is not allowed.
    
    return false;
  }
  
#################################################################################################### --- PRODUCE BINARY STRING
  
  # Initialise $binaryString as FALSE. This will be updated according to the conditions that are met.
  $binaryString = false;
  
  // ----------
  
  if (MIME_TYPES[$mimeType] === 'images') {
    
    # The file says it is an image. Try to recreate it using the GD library.
    # This will destroy most code injections within the file, and remove all EXIF metadata too.
    
    switch ($mimeType) {
      
      case 'image/jpeg' : $imageResource = imagecreatefromjpeg  ($filePath);  break;
      case 'image/png'  : $imageResource = imagecreatefrompng   ($filePath);  break;
      case 'image/gif'  : $imageResource = imagecreatefromgif   ($filePath);  break;
      
      default:
        $imageResource = false;
    }
    
    // ----------
    
    # Check whether the recreated image is a resource of type "gd".
    # If not, the recreation has failed and therefore the image was probably not valid.
    
    # NOTE: Be careful with get_resource_type() if switching from GD to ImageMagick!
    
    # NOTE: Starting with PHP 8.0, get_resource_type() with a GD image argument, will throw a fatal error:
    # PHP Fatal error: Uncaught TypeError: get_resource_type(): Argument #1 ($resource) must be
    # of type resource, GdImage given.
    
    # Manual: If the given handle (parameter) is a resource, get_resource_type() will return
    # a string representing its type. If the type is not identified by this function,
    # the return value will be the string "Unknown".
    
    # get_resource_type() will return NULL and generate an error if handle is not a resource.
    
    if (get_resource_type ($imageResource) === 'gd') {
      
      # Use output buffering to store the image's binary stream in a variable.
      
      ob_start();
      
      // ----------
      
      switch ($mimeType) {
        
        case 'image/jpeg' : imagejpeg ($imageResource, null, 95);   break;
        case 'image/png'  : imagepng  ($imageResource, null, 9);    break;
        case 'image/gif'  : imagegif  ($imageResource);             break;
      }
      
      imagedestroy ($imageResource);
      
      // ----------
      
      # Manual: ob_get_clean() essentially executes both ob_get_contents() and ob_end_clean().
      
      $binaryString = ob_get_clean();
    }
    
  } else {
    
    # All other file types.
    
    $binaryString = file_get_contents ($filePath);
  }
  
#################################################################################################### --- SCAN BINARY STRING
  
  if (isEmpty ($binaryString)) {
    return false;
  }
  
  # Scan the file for occurrences of our blacklisted strings, ie. strings that are associated
  # with coding/injections and should normally not be present within a file binary.
  
  # CAUTION: Text files may give many false positives, as most of the blacklisted strings are also
  # valid words!
  
  # Manual: preg_match_all() returns the number of full pattern matches (which might be zero),
  # or FALSE if an error occurred.
  
  $totalMatches = preg_match_all (COMBINED_BLACKLIST_PATTERN, $binaryString, $blacklistMatches);
  
  // ----------
  
  # We want the check to be successful, but without occurences.
  
  if ($totalMatches === 0) {
    
    # Let's hope it's a simple file! :)
    
    return $binaryString;
    
  } else {
    
    # One or more blacklisted strings were found within the binary! Log this occurence.
    
    $logMessage = 'Blacklisted strings have been found within an image upload!' . "\n" .
                  'File path: ' . $filePath . "\n" .
                  'Total matches: ' . $totalMatches . "\n" .
                  '$_SERVER["REMOTE_ADDR"]: ' . $_SERVER['REMOTE_ADDR'] . "\n";
    
    error_log ($logMessage . print_r ($blacklistMatches, true));
  }
  
  // ----------
  
  return false;
}

?>
